### ISSUE TITLE
[BUG] Crash on startup 1.19.3/2.0.0 Fabric

### ISSUE THREAD

**Issue by Lart-Iste** [Clark919/OrbOfOriginRework#1]
**Hi**, my game crash on startup with this code of exit -1 (0xffffffffffffffff)

**To Reproduce**
I don't know how to reproduce this, I think its specific with my mod list and one or more conflicts, but where and why .... ^^

**Expected behavior**
launch the game properly

**Screenshots & Logs**
https://paste.ee/p/qNcvb

**Mod Version:**
 1.19.3 2.0.0

**Additional context**
Ask me ^^

**Comment by Clark919** [comment]
Hi there, the label indicating this mod is functional for 1.19.3 is incorrect. The mod isn't specifically designed for the latest version, and can only be used with 1.19-1.19.2. I do not plan to update it anytime soon, but if I do it will be properly indicated on the mod page. This has been fixed on the mod page. Cheers.
