### ISSUE TITLE
[BUG] My Issue

### ISSUE THREAD

**Issue by Daemon-fyre** [Clark919/OrbOfOriginRework#2]
**Describe the bug**
When trying to start up my game or server it crashes saying "crashed whilst initializing game" and "could not execute entrypoint stage 'main' due to errors, provided by 'originsorbrework' !"

**To Reproduce**
Steps to reproduce the behavior (add and remove steps as needed, describe clearly):
1. download mod from curseforge
2. put in mods folder
3. start up server/game
4. fail to start up

**Screenshots & Logs**
server log (aternos):   [](https://cdn.discordapp.com/attachments/689543950255915016/1127181686401138738/image.png)
curseforge log:   [](https://cdn.discordapp.com/attachments/689543950255915016/1127182040396218428/image.png)

**Mod Version:**
 1.19.3 1.0.1 FABRIC

**Additional context**
for fabric loader 0.14.21 1.19.3

**Comment by Clark919** [comment]
Hi there. This mod only works for 1.19.2. Only assume only my latest version is available for all of my mods. I do not have plans to update until 1.20 is more commonplace and stable.
